//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MVCDemoEntities : DbContext
    {
        public MVCDemoEntities()
            : base("name=MVCDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseType> CourseTypes { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
    
        public virtual ObjectResult<uspGetMonthWiseCount_Result> uspGetMonthWiseCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetMonthWiseCount_Result>("uspGetMonthWiseCount");
        }
    }
}
